name: Deploy to Hostinger

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Trigger Hostinger Webhook
        run: |
          if [ -z "${{ secrets.HOSTINGER_WEBHOOK_URL }}" ]; then
            echo "Webhook não configurado. Adicione HOSTINGER_WEBHOOK_URL em Settings > Secrets and variables > Actions." && exit 1
          fi
          curl -fsSL -X POST "${{ secrets.HOSTINGER_WEBHOOK_URL }}"

      - name: Wait for site to be online
        env:
          CHECK_URL: ${{ secrets.DEPLOY_CHECK_URL }}
        run: |
          if [ -z "${CHECK_URL}" ]; then echo "Defina DEPLOY_CHECK_URL (ex: https://seu-dominio.com/)" && exit 1; fi
          echo "Verificando ${CHECK_URL}..."
          for i in {1..60}; do
            code=$(curl -Is --max-time 5 "$CHECK_URL" | head -n1 | awk '{print $2}')
            if [ "$code" = "200" ] || [ "$code" = "302" ]; then
              echo "Site online com status $code"; exit 0;
            fi
            echo "Aguardando... tentativa $i (status $code)"; sleep 5;
          done
          echo "Timeout aguardando site online."; exit 1


